services:
  postgres:
    image: postgres:15
    container_name: postgres_prensadao_local
    restart: always
    environment:
      POSTGRES_USER: devPrensadao
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: dbPrensadao
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_prensadao_local
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      
volumes:
  pgdata:
  rabbitmq_data:
  
networks:
  backend:
    driver: bridge